### ISSUE TITLE
AX_PTHREAD: command not found

### ISSUE THREAD

**Issue by pfasante** [ANSSI-FR/libapn#1]
The ax_pthread.m4 file is missing. I suggest you add it to the m4 directory or mention somewhere that it has to be downloaded before `./configure`-ing.

**Comment by jpflori** [comment]
For the recored it's available in autoconf archive.
See: https://www.gnu.org/software/autoconf-archive/ax_pthread.html
On Debian one could `sudo apt install autoconf-archive`
I've added it to the m4 directory on my personal fork and will make a pull request here.

**Comment by jpf-anssi** [comment]
Fixed by e515c68ca73686668afc28464d8e5cc3f609e92d
